name: qemu-virgil
adopt-info: qemu
base: core20
summary: QEMU as a snap, built from latest git with some fancy graphics extras
description: |
  The latest QEMU as a snap package with GTK, SDL2 and Virgil 3D enabled

  To read more about QEMU see https://www.qemu.org/
  To read more about Virgil 3D support go to https://virgil3d.github.io/

  The snap package source can be found at https://github.com/ogra1/qemu-virgil-snap

  If your system supports kvm please make sure to connect the kvm interface after
  you installed qemu-virgl.

  sudo snap connect qemu-virgil:kvm

  Then you can run the VM like below.

  qemu-virgil -enable-kvm -m 2048 -device AC97 -device virtio-vga-gl -display sdl,gl=on \
    -netdev user,id=ethernet.0,hostfwd=tcp::10022-:22 -device rtl8139,netdev=ethernet.0 \
    -soundhw ac97 /path/to/someimage.img

  For qemu-system-arm and qemu-system-aarch64 VMs the snap ships the
  qemu-virgil.arm and qemu-virgil.arm64 commands.

grade: stable
confinement: strict

architectures:
  - build-on: amd64
    run-on: amd64

layout:
  /usr/sbin/smbd:
    bind-file: $SNAP/usr/sbin/smbd
  /usr/share/seabios:
    bind: $SNAP/usr/share/seabios
  /usr/share/qemu:
    bind: $SNAP/usr/share/qemu

apps:
  qemu-virgil:
    extensions: [gnome-3-38]
    command: usr/bin/qemu-system-x86_64
    command-chain: [bin/runner]
    environment:
      LD_LIBRARY_PATH: $SNAP_LIBRARY_PATH:$SNAP/lib/x86_64-linux-gnu:$SNAP/usr/lib/x86_64-linux-gnu:$SNAP/usr/lib:$SNAP/usr/lib/x86_64-linux-gnu/ceph:$SNAP/gnome-platform/usr/lib:$SNAP/gnome-platform/usr/lib/x86_64-linux-gnu:$SNAP/gnome-platform/usr/lib/x86_64-linux-gnu/pulseaudio
    plugs:
      - audio-playback
      - audio-record
      - kvm
      - home
      - opengl
      - process-control
      - raw-usb
      - removable-media
      - screen-inhibit-control
      - network
      - network-bind
      - network-control
      - unity7
  arm64:
    extensions: [gnome-3-38]
    command: usr/bin/qemu-system-aarch64
    command-chain: [bin/runner]
    environment:
      LD_LIBRARY_PATH: $SNAP_LIBRARY_PATH:$SNAP/lib/x86_64-linux-gnu:$SNAP/usr/lib/x86_64-linux-gnu:$SNAP/usr/lib:$SNAP/usr/lib/x86_64-linux-gnu/ceph:$SNAP/gnome-platform/usr/lib:$SNAP/gnome-platform/usr/lib/x86_64-linux-gnu:$SNAP/gnome-platform/usr/lib/x86_64-linux-gnu/pulseaudio
    plugs:
      - audio-playback
      - audio-record
      - kvm
      - home
      - opengl
      - process-control
      - raw-usb
      - removable-media
      - screen-inhibit-control
      - network
      - network-bind
      - network-control
      - unity7
  arm:
    extensions: [gnome-3-38]
    command: usr/bin/qemu-system-arm
    command-chain: [bin/runner]
    environment:
      LD_LIBRARY_PATH: $SNAP_LIBRARY_PATH:$SNAP/lib/x86_64-linux-gnu:$SNAP/usr/lib/x86_64-linux-gnu:$SNAP/usr/lib:$SNAP/usr/lib/x86_64-linux-gnu/ceph:$SNAP/gnome-platform/usr/lib:$SNAP/gnome-platform/usr/lib/x86_64-linux-gnu:$SNAP/gnome-platform/usr/lib/x86_64-linux-gnu/pulseaudio
    plugs:
      - audio-playback
      - audio-record
      - kvm
      - home
      - opengl
      - process-control
      - raw-usb
      - removable-media
      - screen-inhibit-control
      - network
      - network-bind
      - network-control
      - unity7
  qemu-img:
    extensions: [gnome-3-38]
    command: usr/bin/qemu-img
    plugs:
      - home
      - removable-media

parts:
  virgl:
    source: https://gitlab.freedesktop.org/virgl/virglrenderer.git
    source-tag: virglrenderer-0.9.1
    source-depth: 1
    plugin: meson
    meson-parameters:
      - --prefix=/usr
    build-packages:
      - libgbm-dev
      - libdrm-dev
  qemu:
    after: [ virgl ]
    source: git://git.qemu.org/qemu.git
    source-tag: v6.2.0
    source-depth: 1
    plugin: autotools
    autotools-configure-parameters:
      - --prefix=/usr
      - --target-list=x86_64-softmmu,aarch64-softmmu,arm-softmmu
      - --audio-drv-list=pa,sdl
      - --enable-jemalloc
      - --enable-libusb
      - --enable-usb-redir
      - --enable-sdl
      - --enable-spice
      - --enable-xfsctl
    build-environment:
      - ACLOCAL_PATH: /usr/share/aclocal
      - PKG_CONFIG_PATH: $SNAPCRAFT_STAGE/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/pkgconfig:/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/pkgconfig:/usr/lib/pkgconfig:/usr/share/pkgconfig
      - PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/snap/snapcraft/current/bin/scriptlet-bin
      - LD_LIBRARY_PATH: $SNAPCRAFT_STAGE/usr/lib/$SNAPCRAFT_ARCH_TRIPLET:/usr/lib/$SNAPCRAFT_ARCH_TRIPLET:$LD_LIBRARY_PATH
    override-build: |
      snapcraftctl build
      snapcraftctl set-version "$(cat VERSION)"
    build-packages:
      - bison
      - flex
      - gettext
      - libaio-dev
      - libbluetooth-dev
      - libbrlapi-dev
      - libbz2-dev
      - libcap-dev
      - libcap-ng-dev
      - libcacard-dev
      - libcurl4-gnutls-dev
      - libepoxy-dev
      - libfdt-dev
      - libgtk-3-dev
      - libglib2.0-dev
      - libglusterfs-dev
      - libibverbs-dev
      - libiscsi-dev
      - libjemalloc-dev
      - libjpeg8-dev
      - liblzo2-dev
      - libncurses5-dev
      - libnfs-dev
      - libnuma-dev
      - libpango1.0-dev
      - libpixman-1-dev
      - libpulse-dev
      - librbd-dev
      - librdmacm-dev
      - libsasl2-dev
      - libseccomp-dev
      - libsdl2-dev
      - libsdl2-image-dev
      - libsnappy-dev
      - libspice-protocol-dev
      - libspice-server-dev
      - libusb-1.0-0-dev
      - libusbredirhost-dev
      - libusbredirparser-dev
      - libvde-dev
      - libvdeplug-dev
      - libvte-2.91-dev
      - libxml2-dev
      - libx11-dev
      - libxen-dev
      - libzstd-dev
      - ninja-build
      - xfslibs-dev
      - zlib1g-dev
    stage-packages:
      - ipxe-qemu
      - ipxe-qemu-256k-compat-efi-roms
      - libaio1
      - libasn1-8-heimdal
      - libboost-iostreams1.71.0
      - libboost-thread1.71.0
      - libbrlapi0.7
      - libcacard0
      - libcurl3-gnutls
      - libfdt1
      - libgfapi0
      - libgfrpc0
      - libgfxdr0
      - libglusterfs0
      - libgssapi3-heimdal
      - libhcrypto4-heimdal
      - libheimbase1-heimdal
      - libheimntlm0-heimdal
      - libhx509-5-heimdal
      - libibverbs1
      - libiscsi7
      - libjemalloc2
      - libkrb5-26-heimdal
      - libldap-2.4-2
      - libnfs13
      - libnghttp2-14
      - libnuma1
      - libopus0
      - librados2
      - librbd1
      - librdmacm1
      - libroken18-heimdal
      - librtmp1
      - libsasl2-2
      - libsdl2-2.0-0
      - libsdl2-image-2.0-0
      - libsnappy1v5
      - libspice-server1
      - libssh-4
      - libtirpc3
      - liburcu6
      - libusb-1.0-0
      - libusbredirhost1
      - libusbredirparser1
      - libvdeplug2
      - libwind0-heimdal
      - libxencall1
      - libxendevicemodel1
      - libxenevtchn1
      - libxenforeignmemory1
      - libxengnttab1
      - libxenmisc4.11
      - libxenstore3.0
      - libxentoolcore1
      - libxentoollog1
      - libxss1
      - multipath-tools
      - seabios
    prime:
      # Fix execstack warnings
      - -usr/share/qemu/s390-ccw.img
      - -usr/share/qemu/s390-netboot.img
      - -usr/share/qemu/openbios-ppc
      # Remove cruft
      - -usr/share/qemu/qemu-nsis.bmp
      - -lib/systemd/system/multipath-tools-boot.service
  runner:
    after: [ qemu ]
    source: .
    plugin: nil
    override-build: |
      mkdir -p $SNAPCRAFT_PART_INSTALL/bin
      cp -av runner $SNAPCRAFT_PART_INSTALL/bin/
  smbd:
    after: [ runner ]
    plugin: nil
    stage-packages:
      - python3-ldb
      - python3-talloc
      - samba
      - samba-libs
    prime:
      - usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libdcerpc.so*
      - usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libdcerpc-binding.so*
      - usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libdcerpc-server.so*
      - usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libdcerpc-server-core.so*
      - usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libjansson.so*
      - usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libldb.so*
      - usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libndr-krb5pac.so*
      - usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libndr-nbt.so*
      - usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libndr.so*
      - usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libndr-standard.so*
      - usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libnetapi.so*
      - usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libpopt.so*
      - usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libpython2.7.so*
      - usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libpytalloc-util.so*
      - usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libpyldb-util.cpython-38-x86-64-linux-gnu.so*
      - usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libpytalloc-util.cpython-38-x86-64-linux-gnu.so*
      - usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libsamba-*.so*
      - usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libsamdb.so*
      - usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libsmbconf.so*
      - usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libsmbldap.so*
      - usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libtalloc.so*
      - usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libtevent.so*
      - usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libtevent-util.so*
      - usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libwbclient.so*
      - usr/lib/$SNAPCRAFT_ARCH_TRIPLET/samba/*
      - usr/sbin/smbd
  cleanup:
    after: [ smbd ]
    plugin: nil
    build-snaps: [ gnome-3-38-2004 ]
    override-prime: |
      set -eux
      cd /snap/gnome-3-38-2004/current
      find . -type f,l -exec rm -f $SNAPCRAFT_PRIME/{} \;
      for CRUFT in bug lintian man; do
        rm -rf $SNAPCRAFT_PRIME/usr/share/$CRUFT
      done
      find $SNAPCRAFT_PRIME/usr/share/doc/ -type f -not -name 'copyright' -delete
      find $SNAPCRAFT_PRIME/usr/share -type d -empty -delete
